### ISSUE TITLE
Amphora callback failing with "server responded with status of 500 error"

### ISSUE THREAD

**Issue by rob-yerc** [xtellurian/react-amphora#1]
Either using my app or the example app, when trying to authenticate with amphora using the SignInButton component, I am redirected to the login page and enter my username/password, click the Login button, I get  "Uh Oh!  An error occurred while processing your request" message.  See attached screenshot of the webpage and console.log.
![AmphoraCallbackError](https://user-images.githubusercontent.com/60448070/90254524-1e6c4600-de00-11ea-801a-af19edf61abd.png)

**Comment by xtellurian** [comment]
I think I understand the root cause.

0.10.16 added a permanent "remember my choice" for consent when logging into Amphora applications.

It also introduced a bug that could throw when the user choose not to remember.

For that issue, a fix is being deployed in 0.10.17.

**Comment by xtellurian** [comment]
@rob-yerc v0.10.17 has been deployed.

Are you still experiencing this error?

**Comment by rob-yerc** [comment]
Seems to be working!  Thanks!
